### PR TITLE
Codeclimate

### PR DESCRIPTION
**Pull request by whereismyjetpack**

### CODE REVIEW

**Comment by whereismyjetpack** [comment]
will squash on merge. fumbling around with codeclimate not being compatable with simplecov 0.18

**Comment by whereismyjetpack** [comment]
fixes #12 i think code-climate only runs on the default branch, so hopefully after this is merged we see some stuff

**Comment by awead** [comment]
@whereismyjetpack SS4 is also using simplecov ~ 0.17 so there may be something going on there. See psu-stewardship/scholarsphere-4#285

**Comment by whereismyjetpack** [comment]
https://github.com/codeclimate/test-reporter/issues/413 following this issue before we can update

**Comment by whereismyjetpack** [comment]
https://github.com/codeclimate/test-reporter/issues/413 following this issue before we can update

**Pull request merged**
